### ISSUE TITLE
Unhandled exception in version 2.0

### ISSUE THREAD

**Issue by fultrim** [sunkid/WorldModes#1]
I get the following error when i try to use the gamemode or any of the alias commands.  We are using Essentials 2.6.3 w/GroupManager for perms and Waypoint 1.6 for multi-world management.  We are using worldmodes 2.0.

2011-10-13 08:06:05 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'gm' in plugin WorldModes v2.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:163)
at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:355)
at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:757)
at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:722)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:715)
at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:471)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
Caused by: java.lang.NoClassDefFoundError: com/iminurnetz/bukkit/permissions/PermissionHandler
at com.iminurnetz.bukkit.plugin.worldmodes.WorldModesPlugin.onCommand(WorldModesPlugin.java:104)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
... 12 more

**Comment by sunkid** [comment]
You need to install BaseBukkitPlugin.jar as per the instructions.
